### ISSUE TITLE
Jira Authenticator: Prüft, ob das Projekt, für das sich der Benutzer anmelden will, auch in der Liste ist.

### ISSUE THREAD

**Issue by fischJan** [qualicen/specmate#198]
**User Story**
Technisches Requirement

**Acceptance Criteria**
- Der Authenticator prüft, ob das Projekt, für das sich der Nutzer anmelden will, in der Liste der Projekte ist, für das der Nutzer Leserechte hat.

**Comment by hauptmab** [comment]
**Clarifying question:** _.. für das der Nutzer Schreibrechte hat._ 

This acceptance criteria sound like users MUST HAVE write credentials to a jira project in order to log in th the corresponding specmate-project. Is this intended?

_Concern 1:_ As far as I know, this would be new behaviour (there are no authorization semantics implemented yet). This should be moved to a new issue (if required).
_Concern 2:_ A user might just have read credentials to a jira project but, nevertheless, wants to create a model for a user story (As far as I know, this is the current behaviour).

@fischJan please clarify this issue.

**Comment by fischJan** [comment]
Hast Recht, es geht hier nicht um Schreibrechte sondern allein um Leserechte. Das reicht ja aus :) Ich update das Akzeptanzkriterium.
