### ISSUE TITLE
Extended Search

### ISSUE THREAD

**Issue by fischJan** [qualicen/specmate#355]
# Story

As a user, I want to filter work items efficiently and intuitively, so that I can find them quickly.

# Acceptance criteria:

- There is a panel for extended search
- The user can search by name
- The user can search by extId
- The user can search by description
- There is a preview of the search results (e.g., as typeahead)

**Comment by sebeder** [comment]
# Story

As a user, I want to filter work items efficiently and intuitively, so that I can find them quickly.

# Acceptance criteria:

- There is a panel for extended search
- The user can search by name
- The user can search by extId
- The user can search by description
- There is a preview of the search results (e.g., as typeahead)
